// src/components/CartDrawer.vue
<template>
  <Teleport to="body">
    <transition name="slide">
      <div
        v-if="isDrawerOpen"
        class="fixed inset-y-0 right-0 z-[70] w-full md:w-96 bg-stone-50 shadow-2xl flex flex-col"
      >
        <!-- Header -->
        <div class="flex items-center justify-between p-6 border-b border-stone-200">
          <h2 class="text-xl font-serif text-stone-900">Your Cart</h2>
          <button @click="toggleDrawer" class="p-2 text-stone-500 hover:text-stone-900 transition-colors">
            <X class="w-6 h-6" />
          </button>
        </div>

        <!-- Empty State -->
        <div v-if="cartItems.length === 0" class="flex-1 flex flex-col items-center justify-center p-8 text-stone-400">
          <ShoppingBag class="w-12 h-12 mb-4 opacity-50" />
          <p class="text-lg font-medium">Your cart is empty.</p>
          <router-link to="/collections" @click="toggleDrawer" class="mt-4 text-amber-800 hover:underline">
            Start Shopping
          </router-link>
        </div>

        <!-- Items List -->
        <div v-else class="flex-1 overflow-y-auto p-6 space-y-6">
          <div v-for="item in cartItems" :key="item.id" class="flex items-start gap-4 pb-6 border-b border-stone-100 last:border-0">
            <div class="w-20 h-24 bg-stone-200 flex-shrink-0 overflow-hidden rounded-sm">
              <img :src="item.image" :alt="item.name" class="w-full h-full object-cover" />
            </div>
            <div class="flex-1">
              <div class="flex justify-between items-start mb-1">
                <h3 class="font-serif text-stone-900 line-clamp-2 leading-tight">{{ item.name }}</h3>
                <button @click="removeFromCart(item.id)" class="text-stone-400 hover:text-red-500 transition-colors">
                  <Trash2 class="w-4 h-4" />
                </button>
              </div>
              <p class="text-stone-500 text-sm mb-2">{{ item.price }}</p>
              <div class="flex items-center justify-between">
                <div class="flex items-center border border-stone-200 rounded-sm">
                  <span class="px-2 text-sm text-stone-900">Qty: {{ item.quantity }}</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Footer -->
        <div v-if="cartItems.length > 0" class="p-6 bg-stone-100 border-t border-stone-200">
          <div class="flex justify-between items-center mb-4">
            <span class="text-stone-600 font-medium">Subtotal</span>
            <span class="text-stone-900 font-bold text-lg">${{ cartTotal }}</span>
          </div>
          <button class="w-full bg-stone-900 text-stone-50 py-3 font-medium uppercase tracking-widest hover:bg-stone-800 transition-colors">
            Checkout
          </button>
        </div>
      </div>
    </transition>

    <!-- Backdrop -->
    <transition name="fade">
      <div
        v-if="isDrawerOpen"
        class="fixed inset-0 z-[65] bg-stone-900/50 backdrop-blur-sm"
        @click="toggleDrawer"
      ></div>
    </transition>
  </Teleport>
</template>

<script setup lang="ts">
import { useCart } from '../composables/useCart';
import { X, ShoppingBag, Trash2 } from 'lucide-vue-next';

const { isDrawerOpen, toggleDrawer, cartItems, removeFromCart, cartTotal } = useCart();
</script>

<style scoped>
.slide-enter-active,
.slide-leave-active {
  transition: transform 0.3s ease-out;
}

.slide-enter-from,
.slide-leave-to {
  transform: translateX(100%);
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>

// src/components/CartDrawer.tsx
import { useEffect } from 'react'
import { Link } from 'react-router-dom'
import { useCart, useCartTotal, lineProduct } from '../store/cart'
import { formatPrice } from '../data/products'
import ProductArt from './ProductArt'
import { CloseIcon, MinusIcon, PlusIcon, ArrowIcon } from './Icons'

const FREE_SHIP = 150

export default function CartDrawer() {
  const { isOpen, close, lines, setQty, remove } = useCart()
  const total = useCartTotal()
  const remaining = Math.max(0, FREE_SHIP - total)
  const progress = Math.min(100, (total / FREE_SHIP) * 100)

  useEffect(() => {
    document.body.style.overflow = isOpen ? 'hidden' : ''
    return () => {
      document.body.style.overflow = ''
    }
  }, [isOpen])

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-50">
      <div className="absolute inset-0 bg-ink/40 backdrop-blur-sm" onClick={close} />
      <aside className="absolute inset-y-0 right-0 flex w-full max-w-md animate-slide-in flex-col bg-cream shadow-2xl">
        <div className="flex items-center justify-between border-b border-ink/10 px-5 py-4">
          <h2 className="font-display text-xl">Your bag</h2>
          <button aria-label="Close cart" onClick={close}>
            <CloseIcon />
          </button>
        </div>

        {lines.length === 0 ? (
          <div className="flex flex-1 flex-col items-center justify-center gap-4 px-6 text-center">
            <p className="font-display text-2xl">Nothing in here yet.</p>
            <p className="text-sm text-ink-soft">
              Good bags don’t buy themselves.
            </p>
            <button onClick={close} className="btn-primary mt-2">
              Start shopping
            </button>
          </div>
        ) : (
          <>
            {/* Free-shipping progress */}
            <div className="border-b border-ink/10 px-5 py-3">
              <p className="text-xs text-ink-soft">
                {remaining > 0 ? (
                  <>
                    You’re <span className="font-medium text-ink">{formatPrice(remaining)}</span> away
                    from free shipping
                  </>
                ) : (
                  <span className="font-medium text-moss">You’ve unlocked free shipping ✦</span>
                )}
              </p>
              <div className="mt-2 h-1.5 overflow-hidden rounded-full bg-bone-200">
                <div
                  className="h-full rounded-full bg-clay transition-all duration-500"
                  style={{ width: `${progress}%` }}
                />
              </div>
            </div>

            <div className="flex-1 overflow-y-auto px-5 py-4">
              <ul className="space-y-5">
                {lines.map((line) => {
                  const product = lineProduct(line)
                  if (!product) return null
                  return (
                    <li key={`${line.productId}-${line.color}`} className="flex gap-4">
                      <Link
                        to={`/product/${product.slug}`}
                        onClick={close}
                        className="h-24 w-24 shrink-0 overflow-hidden rounded-xl bg-bone-200"
                      >
                        <ProductArt product={product} className="h-full w-full" />
                      </Link>
                      <div className="flex flex-1 flex-col">
                        <div className="flex justify-between gap-2">
                          <div>
                            <h3 className="font-display text-base leading-tight">{product.name}</h3>
                            <p className="text-xs text-ink-soft">{line.color}</p>
                          </div>
                          <span className="text-sm tabular-nums">
                            {formatPrice(product.price * line.qty)}
                          </span>
                        </div>
                        <div className="mt-auto flex items-center justify-between">
                          <div className="flex items-center gap-3 rounded-full border border-ink/20 px-2 py-1">
                            <button
                              aria-label="Decrease quantity"
                              onClick={() => setQty(line.productId, line.color, line.qty - 1)}
                            >
                              <MinusIcon />
                            </button>
                            <span className="w-4 text-center text-sm tabular-nums">{line.qty}</span>
                            <button
                              aria-label="Increase quantity"
                              onClick={() => setQty(line.productId, line.color, line.qty + 1)}
                            >
                              <PlusIcon />
                            </button>
                          </div>
                          <button
                            onClick={() => remove(line.productId, line.color)}
                            className="link-underline text-xs text-ink-soft"
                          >
                            Remove
                          </button>
                        </div>
                      </div>
                    </li>
                  )
                })}
              </ul>
            </div>

            <div className="border-t border-ink/10 px-5 py-5">
              <div className="flex items-center justify-between">
                <span className="font-sans text-sm uppercase tracking-widest text-ink-soft">
                  Subtotal
                </span>
                <span className="font-display text-2xl tabular-nums">{formatPrice(total)}</span>
              </div>
              <p className="mt-1 text-xs text-ink-soft">Taxes and shipping calculated at checkout.</p>
              <Link to="/checkout" onClick={close} className="btn-primary mt-4 w-full">
                Checkout
                <ArrowIcon />
              </Link>
            </div>
          </>
        )}
      </aside>
    </div>
  )
}
